version: "3.9"  
services:

  frontend:
      image: main/webapp
      ports:
        - "443:8043"
      networks:
        - front-tier
        - back-tier
      configs:
        - httpd-config
      secrets:
        - server-certificate

volumes:
  db-data:
    driver: flocker
    driver_opts:
      size: "10GiB"

spring-boot:
    image: imagem-spring-boot
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: spring-boot-api-2
    expose:
      - 5000
    restart: always

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true